---
# This playbook will install MariaDB and create db user and give permissions.

- name: Install MariaDB package
  dnf: name=MariaDB-server state=latest
  disablerepo: AppStream #MariaDB-server 10.4 をmariadb repoからインストールするため

  dnf: name={{ item }} state=latest
  with_items:
   - python3-PyMySQL #MySQL-python (python3系対応の為ドライバ変更)
   - python3-libselinux #libselinux-pythonの後継
   - python3-libsemanage #libsemanage-pythonの後継

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mariadb

- name: Create MariaDB log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775

- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes

- name: insert firewalld rule
  firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes
