---
- name: Install VMware Tools
  dnf: name=vm-open-tools state=latest

- name: Copy the NGINX repository definition
  copy: src=nginx.repo dest=/etc/yum.repos.d/

- name: Copy the EPEL repository definition
  copy: src=epel.repo dest=/etc/yum.repos.d/

- name: Copy the remi-php74 repository definition
  copy: src=remi-php74.repo dest=/etc/yum.repos.d/

- name: Copy the Mariadb repository definition
  copy: src=Mariadb.repo dest=/etc/yum.repos.d/

- name: Create the GPG key for NGINX
  copy: src=RPM-GPG-KEY-NGINX dest=/etc/pki/rpm-gpg

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-8 dest=/etc/pki/rpm-gpg

- name: Create the GPG key for REMI
  copy: src=RPM-GPG-KEY-remi dest=/etc/pki/rpm-gpg
  
- name: Install Firewalld
  yum: name=firewalld state=present

- name: Firewalld service state
  service: name=firewalld state=started enabled=yes

- name: Kernel Update Script
  copy: src=startup.sh dest=/root/　mode=0777

- name: test script
  copy: src=test.sh dest=/root/
