---
- name: Install libonig.so.5()  
  dnf: name=https://rpmfind.net/linux/centos/8.2.2004/AppStream/x86_64/os/Packages/oniguruma-6.8.2-1.el8.x86_64.rpm

- name: Install php-fpm and deps  
  dnf: name={{ item }} state=latest disablerepo=AppStream
  with_items:
    - php-fpm
    - php-enchant
    # - php-IDNA_Convert 2014年にて開発終了のためコメントアウト
    - php-mbstring
    - php-mysqlnd
    # - php-PHPMailer remi-php74 から外されたためコメントアウト
    - php-process
    # - php-simplepie remi-php74 から外されたためコメントアウト
    - php-xml
    - php-gd

- name: Disable default pool
  command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
  notify: restart php-fpm

- name: Copy php-fpm configuration
  template: src=wordpress.conf dest=/etc/php-fpm.d/
  notify: restart php-fpm
