---
- name: Install php-fpm and deps
  yum: name={{ item }} state=latest
  with_items:
    - php
    - php-fpm
    - php-enchant
    - php-IDNA_Convert
    - php-mbstring
    - php-mysqlnd
    - php-PHPMailer
    - php-process
    - php-simplepie
    - php-xml
    - php-gd

- name: Disable default pool
  command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
  notify: restart php-fpm

- name: Copy php-fpm configuration
  template: src=wordpress.conf dest=/etc/php-fpm.d/
  notify: restart php-fpm

- name: Copy PHP7.4 configuration for wordpress 1
  command: sed -i -e "402 s/128M/1G/g" /etc/php.ini

- name: Copy PHP7.4 configuration for wordpress 2
  command: sed -i -e "687 s/8M/10G/g" /etc/php.ini

- name: Copy PHP7.4 configuration for wordpress 3
  command: sed -i -e "839 s/2M/10G/g" /etc/php.ini
  notify: restart php-fpm